/// <summary> OWASP Enterprise Security API (ESAPI)
/// 
/// This file is part of the Open Web Application Security Project (OWASP)
/// Enterprise Security API (ESAPI) project. For details, please see
/// http://www.owasp.org/esapi.
/// 
/// Copyright (c) 2007 - The OWASP Foundation
/// 
/// The ESAPI is published by OWASP under the LGPL. You should read and accept the
/// LICENSE before you use, modify, and/or redistribute this software.
/// 
/// </summary>
/// <author>  Jeff Williams <a href="http://www.aspectsecurity.com">Aspect Security</a>
/// </author>
/// <created>  2007 </created>
using System;
//UPGRADE_TODO: The type 'junit.framework.Test' could not be found. If it was not included in the conversion, there may be compiler issues. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1262'"
using Test = junit.framework.Test;
//UPGRADE_TODO: The type 'junit.framework.TestCase' could not be found. If it was not included in the conversion, there may be compiler issues. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1262'"
using TestCase = junit.framework.TestCase;
//UPGRADE_TODO: The type 'junit.framework.TestSuite' could not be found. If it was not included in the conversion, there may be compiler issues. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1262'"
using TestSuite = junit.framework.TestSuite;
namespace org.owasp.esapi
{
	
	/// <summary> The Class AllTests.
	/// 
	/// </summary>
	/// <author>  Jeff Williams (jeff.williams@aspectsecurity.com)
	/// </author>
	public class AllTests:TestCase
	{
		
		/// <summary> Instantiates a new all tests.
		/// 
		/// </summary>
		/// <param name="testName">the test name
		/// </param>
		public AllTests(System.String testName):base(testName)
		{
		}
		
		/* (non-Javadoc)
		* @see junit.framework.TestCase#setUp()
		*/
		protected internal virtual void  setUp()
		{
			// none
		}
		
		/* (non-Javadoc)
		* @see junit.framework.TestCase#tearDown()
		*/
		protected internal virtual void  tearDown()
		{
			// none
		}
		
		/// <summary> suite method automatically generated by JUnit module.
		/// 
		/// </summary>
		/// <returns> the test
		/// </returns>
		public static Test suite()
		{
			System.Console.Out.WriteLine("INITIALIZING ALL TESTS");
			
			// The following property must be set in order for the tests to find the resources directory
			// You can set it here, or you can launch JUnit with the VM argument
			//     -Dorg.owasp.espai.resources="/Users/...ESAPI/test/testresources"
			// System.setProperty(SecurityConfiguration.RESOURCE_DIRECTORY, "C:/Users/.../ESAPI/test/testresources");
			
			
			// clear the User file to prep for tests
			System.IO.FileInfo file = new System.IO.FileInfo(((SecurityConfiguration) ESAPI.securityConfiguration()).ResourceDirectory.FullName + "\\" + "users.txt");
			System.IO.StreamWriter writer = null;
			try
			{
				//UPGRADE_WARNING: At least one expression was used more than once in the target code. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1181'"
				//UPGRADE_TODO: Constructor 'java.io.FileWriter.FileWriter' was converted to 'System.IO.StreamWriter' which has a different behavior. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1073_javaioFileWriterFileWriter_javaioFile'"
				//UPGRADE_TODO: Class 'java.io.FileWriter' was converted to 'System.IO.StreamWriter' which has a different behavior. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1073_javaioFileWriter'"
				writer = new System.IO.StreamWriter(new System.IO.StreamWriter(file.FullName, false, System.Text.Encoding.Default).BaseStream, new System.IO.StreamWriter(file.FullName, false, System.Text.Encoding.Default).Encoding);
				//UPGRADE_TODO: Method 'java.io.PrintWriter.println' was converted to 'System.IO.TextWriter.WriteLine' which has a different behavior. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1073_javaioPrintWriterprintln_javalangString'"
				writer.WriteLine("# This is the user file associated with the ESAPI library from http://www.owasp.org");
				//UPGRADE_TODO: Method 'java.io.PrintWriter.println' was converted to 'System.IO.TextWriter.WriteLine' which has a different behavior. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1073_javaioPrintWriterprintln_javalangString'"
				writer.WriteLine("# accountName | hashedPassword | roles | locked | enabled | rememberToken | csrfToken | oldPasswordHashes | lastPasswordChangeTime | lastLoginTime | lastFailedLoginTime | expirationTime | failedLoginCount");
				//UPGRADE_TODO: Method 'java.io.PrintWriter.println' was converted to 'System.IO.TextWriter.WriteLine' which has a different behavior. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1073_javaioPrintWriterprintln'"
				writer.WriteLine();
				writer.Flush();
			}
			catch (System.IO.IOException e)
			{
			}
			finally
			{
				if (writer != null)
				{
					//UPGRADE_NOTE: Exceptions thrown by the equivalent in .NET of method 'java.io.PrintWriter.close' may be different. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1099'"
					writer.Close();
				}
			}
			
			TestSuite suite = new TestSuite("AllTests");
			suite.addTest(org.owasp.esapi.LoggerTest.suite());
			suite.addTest(org.owasp.esapi.UserTest.suite());
			suite.addTest(org.owasp.esapi.RandomizerTest.suite());
			suite.addTest(org.owasp.esapi.AccessControllerTest.suite());
			suite.addTest(org.owasp.esapi.HTTPUtilitiesTest.suite());
			suite.addTest(org.owasp.esapi.ValidatorTest.suite());
			suite.addTest(org.owasp.esapi.EncryptorTest.suite());
			suite.addTest(org.owasp.esapi.IntrusionDetectorTest.suite());
			suite.addTest(org.owasp.esapi.AccessReferenceMapTest.suite());
			suite.addTest(org.owasp.esapi.ExecutorTest.suite());
			suite.addTest(org.owasp.esapi.EncoderTest.suite());
			suite.addTest(org.owasp.esapi.EncryptedPropertiesTest.suite());
			suite.addTest(org.owasp.esapi.AuthenticatorTest.suite());
			suite.addTest(org.owasp.esapi.errors.EnterpriseSecurityExceptionTest.suite());
			return suite;
		}
	}
}